name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
title: "[DOCS] <description>"
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: file_path
    attributes:
      label: filepath
      description: Please mention the path of the file in which you found the documentation error
    validations:
      required: true
   - type: textarea
    id: line_number
    attributes:
      label: linenumber
      description: Please Enter the Line number in which the error was found
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information about the execution environment such as OS name and version
      description: 
    validations:
      required: false
   - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: want_to_work
    attributes:
      label: I want to work on this (optional)
      description: Select if you want to work on this Issue
      options:
        - label: I want to work on this issue
          required: false